name: 'Terraform'
on:
  pull_request:
   
  push:
    branches:
      - main
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

  tflint:
    name: tflint
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Cache plugin dir
        uses: actions/checkout@v2
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl')}}

      - uses: terraform-linters/tflint-action@v1
        name: Setup TFLint
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          tflint_version: latest

      - name: Show version
        run: tflint --version

      - name: tflint init
        run: tflint --init
        
      - name: run tflint
        run: tflint -f compact
        
